package com.fido.tro.ast;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;

public class PhpParserListenerAll extends PhpParserBaseListener {
    @Override public void enterHtmlDocument(PhpParser.HtmlDocumentContext ctx) { System.out.println("enterHtmlDocument: " + ctx.getText()); }
    @Override public void exitHtmlDocument(PhpParser.HtmlDocumentContext ctx) { System.out.println("exitHtmlDocument: " + ctx.getText()); }
    @Override public void enterHtmlElementOrPhpBlock(PhpParser.HtmlElementOrPhpBlockContext ctx) { System.out.println("enterHtmlElementOrPhpBlock: " + ctx.getText()); }
    @Override public void exitHtmlElementOrPhpBlock(PhpParser.HtmlElementOrPhpBlockContext ctx) { System.out.println("exitHtmlElementOrPhpBlock: " + ctx.getText()); }
    @Override public void enterHtmlElements(PhpParser.HtmlElementsContext ctx) { System.out.println("enterHtmlElements: " + ctx.getText()); }
    @Override public void exitHtmlElements(PhpParser.HtmlElementsContext ctx) { System.out.println("exitHtmlElements: " + ctx.getText()); }
    @Override public void enterHtmlElement(PhpParser.HtmlElementContext ctx) { System.out.println("enterHtmlElement: " + ctx.getText()); }
    @Override public void exitHtmlElement(PhpParser.HtmlElementContext ctx) { System.out.println("exitHtmlElement: " + ctx.getText()); }
    @Override public void enterScriptTextPart(PhpParser.ScriptTextPartContext ctx) { System.out.println("enterScriptTextPart: " + ctx.getText()); }
    @Override public void exitScriptTextPart(PhpParser.ScriptTextPartContext ctx) { System.out.println("exitScriptTextPart: " + ctx.getText()); }
    @Override public void enterPhpBlock(PhpParser.PhpBlockContext ctx) { System.out.println("enterPhpBlock: " + ctx.getText()); }
    @Override public void exitPhpBlock(PhpParser.PhpBlockContext ctx) { System.out.println("exitPhpBlock: " + ctx.getText()); }
    @Override public void enterImportStatement(PhpParser.ImportStatementContext ctx) { System.out.println("enterImportStatement: " + ctx.getText()); }
    @Override public void exitImportStatement(PhpParser.ImportStatementContext ctx) { System.out.println("exitImportStatement: " + ctx.getText()); }
    @Override public void enterTopStatement(PhpParser.TopStatementContext ctx) { System.out.println("enterTopStatement: " + ctx.getText()); }
    @Override public void exitTopStatement(PhpParser.TopStatementContext ctx) { System.out.println("exitTopStatement: " + ctx.getText()); }
    @Override public void enterUseDeclaration(PhpParser.UseDeclarationContext ctx) { System.out.println("enterUseDeclaration: " + ctx.getText()); }
    @Override public void exitUseDeclaration(PhpParser.UseDeclarationContext ctx) { System.out.println("exitUseDeclaration: " + ctx.getText()); }
    @Override public void enterUseDeclarationContentList(PhpParser.UseDeclarationContentListContext ctx) { System.out.println("enterUseDeclarationContentList: " + ctx.getText()); }
    @Override public void exitUseDeclarationContentList(PhpParser.UseDeclarationContentListContext ctx) { System.out.println("exitUseDeclarationContentList: " + ctx.getText()); }
    @Override public void enterUseDeclarationContent(PhpParser.UseDeclarationContentContext ctx) { System.out.println("enterUseDeclarationContent: " + ctx.getText()); }
    @Override public void exitUseDeclarationContent(PhpParser.UseDeclarationContentContext ctx) { System.out.println("exitUseDeclarationContent: " + ctx.getText()); }
    @Override public void enterNamespaceDeclaration(PhpParser.NamespaceDeclarationContext ctx) { System.out.println("enterNamespaceDeclaration: " + ctx.getText()); }
    @Override public void exitNamespaceDeclaration(PhpParser.NamespaceDeclarationContext ctx) { System.out.println("exitNamespaceDeclaration: " + ctx.getText()); }
    @Override public void enterNamespaceStatement(PhpParser.NamespaceStatementContext ctx) { System.out.println("enterNamespaceStatement: " + ctx.getText()); }
    @Override public void exitNamespaceStatement(PhpParser.NamespaceStatementContext ctx) { System.out.println("exitNamespaceStatement: " + ctx.getText()); }
    @Override public void enterFunctionDeclaration(PhpParser.FunctionDeclarationContext ctx) { System.out.println("enterFunctionDeclaration: " + ctx.getText()); }
    @Override public void exitFunctionDeclaration(PhpParser.FunctionDeclarationContext ctx) { System.out.println("exitFunctionDeclaration: " + ctx.getText()); }
    @Override public void enterClassDeclaration(PhpParser.ClassDeclarationContext ctx) { System.out.println("enterClassDeclaration: " + ctx.getText()); }
    @Override public void exitClassDeclaration(PhpParser.ClassDeclarationContext ctx) { System.out.println("exitClassDeclaration: " + ctx.getText()); }
    @Override public void enterClassEntryType(PhpParser.ClassEntryTypeContext ctx) { System.out.println("enterClassEntryType: " + ctx.getText()); }
    @Override public void exitClassEntryType(PhpParser.ClassEntryTypeContext ctx) { System.out.println("exitClassEntryType: " + ctx.getText()); }
    @Override public void enterInterfaceList(PhpParser.InterfaceListContext ctx) { System.out.println("enterInterfaceList: " + ctx.getText()); }
    @Override public void exitInterfaceList(PhpParser.InterfaceListContext ctx) { System.out.println("exitInterfaceList: " + ctx.getText()); }
    @Override public void enterTypeParameterListInBrackets(PhpParser.TypeParameterListInBracketsContext ctx) { System.out.println("enterTypeParameterListInBrackets: " + ctx.getText()); }
    @Override public void exitTypeParameterListInBrackets(PhpParser.TypeParameterListInBracketsContext ctx) { System.out.println("exitTypeParameterListInBrackets: " + ctx.getText()); }
    @Override public void enterTypeParameterList(PhpParser.TypeParameterListContext ctx) { System.out.println("enterTypeParameterList: " + ctx.getText()); }
    @Override public void exitTypeParameterList(PhpParser.TypeParameterListContext ctx) { System.out.println("exitTypeParameterList: " + ctx.getText()); }
    @Override public void enterTypeParameterWithDefaultsList(PhpParser.TypeParameterWithDefaultsListContext ctx) { System.out.println("enterTypeParameterWithDefaultsList: " + ctx.getText()); }
    @Override public void exitTypeParameterWithDefaultsList(PhpParser.TypeParameterWithDefaultsListContext ctx) { System.out.println("exitTypeParameterWithDefaultsList: " + ctx.getText()); }
    @Override public void enterTypeParameterDecl(PhpParser.TypeParameterDeclContext ctx) { System.out.println("enterTypeParameterDecl: " + ctx.getText()); }
    @Override public void exitTypeParameterDecl(PhpParser.TypeParameterDeclContext ctx) { System.out.println("exitTypeParameterDecl: " + ctx.getText()); }
    @Override public void enterTypeParameterWithDefaultDecl(PhpParser.TypeParameterWithDefaultDeclContext ctx) { System.out.println("enterTypeParameterWithDefaultDecl: " + ctx.getText()); }
    @Override public void exitTypeParameterWithDefaultDecl(PhpParser.TypeParameterWithDefaultDeclContext ctx) { System.out.println("exitTypeParameterWithDefaultDecl: " + ctx.getText()); }
    @Override public void enterGenericDynamicArgs(PhpParser.GenericDynamicArgsContext ctx) { System.out.println("enterGenericDynamicArgs: " + ctx.getText()); }
    @Override public void exitGenericDynamicArgs(PhpParser.GenericDynamicArgsContext ctx) { System.out.println("exitGenericDynamicArgs: " + ctx.getText()); }
    @Override public void enterAttributes(PhpParser.AttributesContext ctx) { System.out.println("enterAttributes: " + ctx.getText()); }
    @Override public void exitAttributes(PhpParser.AttributesContext ctx) { System.out.println("exitAttributes: " + ctx.getText()); }
    @Override public void enterAttributesGroup(PhpParser.AttributesGroupContext ctx) { System.out.println("enterAttributesGroup: " + ctx.getText()); }
    @Override public void exitAttributesGroup(PhpParser.AttributesGroupContext ctx) { System.out.println("exitAttributesGroup: " + ctx.getText()); }
    @Override public void enterAttribute(PhpParser.AttributeContext ctx) { System.out.println("enterAttribute: " + ctx.getText()); }
    @Override public void exitAttribute(PhpParser.AttributeContext ctx) { System.out.println("exitAttribute: " + ctx.getText()); }
    @Override public void enterAttributeArgList(PhpParser.AttributeArgListContext ctx) { System.out.println("enterAttributeArgList: " + ctx.getText()); }
    @Override public void exitAttributeArgList(PhpParser.AttributeArgListContext ctx) { System.out.println("exitAttributeArgList: " + ctx.getText()); }
    @Override public void enterAttributeNamedArgList(PhpParser.AttributeNamedArgListContext ctx) { System.out.println("enterAttributeNamedArgList: " + ctx.getText()); }
    @Override public void exitAttributeNamedArgList(PhpParser.AttributeNamedArgListContext ctx) { System.out.println("exitAttributeNamedArgList: " + ctx.getText()); }
    @Override public void enterAttributeNamedArg(PhpParser.AttributeNamedArgContext ctx) { System.out.println("enterAttributeNamedArg: " + ctx.getText()); }
    @Override public void exitAttributeNamedArg(PhpParser.AttributeNamedArgContext ctx) { System.out.println("exitAttributeNamedArg: " + ctx.getText()); }
    @Override public void enterInnerStatementList(PhpParser.InnerStatementListContext ctx) { System.out.println("enterInnerStatementList: " + ctx.getText()); }
    @Override public void exitInnerStatementList(PhpParser.InnerStatementListContext ctx) { System.out.println("exitInnerStatementList: " + ctx.getText()); }
    @Override public void enterInnerStatement(PhpParser.InnerStatementContext ctx) { System.out.println("enterInnerStatement: " + ctx.getText()); }
    @Override public void exitInnerStatement(PhpParser.InnerStatementContext ctx) { System.out.println("exitInnerStatement: " + ctx.getText()); }
    @Override public void enterStatement(PhpParser.StatementContext ctx) { System.out.println("enterStatement: " + ctx.getText()); }
    @Override public void exitStatement(PhpParser.StatementContext ctx) { System.out.println("exitStatement: " + ctx.getText()); }
    @Override public void enterEmptyStatement(PhpParser.EmptyStatementContext ctx) { System.out.println("enterEmptyStatement: " + ctx.getText()); }
    @Override public void exitEmptyStatement(PhpParser.EmptyStatementContext ctx) { System.out.println("exitEmptyStatement: " + ctx.getText()); }
    @Override public void enterBlockStatement(PhpParser.BlockStatementContext ctx) { System.out.println("enterBlockStatement: " + ctx.getText()); }
    @Override public void exitBlockStatement(PhpParser.BlockStatementContext ctx) { System.out.println("exitBlockStatement: " + ctx.getText()); }
    @Override public void enterIfStatement(PhpParser.IfStatementContext ctx) { System.out.println("enterIfStatement: " + ctx.getText()); }
    @Override public void exitIfStatement(PhpParser.IfStatementContext ctx) { System.out.println("exitIfStatement: " + ctx.getText()); }
    @Override public void enterElseIfStatement(PhpParser.ElseIfStatementContext ctx) { System.out.println("enterElseIfStatement: " + ctx.getText()); }
    @Override public void exitElseIfStatement(PhpParser.ElseIfStatementContext ctx) { System.out.println("exitElseIfStatement: " + ctx.getText()); }
    @Override public void enterElseIfColonStatement(PhpParser.ElseIfColonStatementContext ctx) { System.out.println("enterElseIfColonStatement: " + ctx.getText()); }
    @Override public void exitElseIfColonStatement(PhpParser.ElseIfColonStatementContext ctx) { System.out.println("exitElseIfColonStatement: " + ctx.getText()); }
    @Override public void enterElseStatement(PhpParser.ElseStatementContext ctx) { System.out.println("enterElseStatement: " + ctx.getText()); }
    @Override public void exitElseStatement(PhpParser.ElseStatementContext ctx) { System.out.println("exitElseStatement: " + ctx.getText()); }
    @Override public void enterElseColonStatement(PhpParser.ElseColonStatementContext ctx) { System.out.println("enterElseColonStatement: " + ctx.getText()); }
    @Override public void exitElseColonStatement(PhpParser.ElseColonStatementContext ctx) { System.out.println("exitElseColonStatement: " + ctx.getText()); }
    @Override public void enterWhileStatement(PhpParser.WhileStatementContext ctx) { System.out.println("enterWhileStatement: " + ctx.getText()); }
    @Override public void exitWhileStatement(PhpParser.WhileStatementContext ctx) { System.out.println("exitWhileStatement: " + ctx.getText()); }
    @Override public void enterDoWhileStatement(PhpParser.DoWhileStatementContext ctx) { System.out.println("enterDoWhileStatement: " + ctx.getText()); }
    @Override public void exitDoWhileStatement(PhpParser.DoWhileStatementContext ctx) { System.out.println("exitDoWhileStatement: " + ctx.getText()); }
    @Override public void enterForStatement(PhpParser.ForStatementContext ctx) { System.out.println("enterForStatement: " + ctx.getText()); }
    @Override public void exitForStatement(PhpParser.ForStatementContext ctx) { System.out.println("exitForStatement: " + ctx.getText()); }
    @Override public void enterForInit(PhpParser.ForInitContext ctx) { System.out.println("enterForInit: " + ctx.getText()); }
    @Override public void exitForInit(PhpParser.ForInitContext ctx) { System.out.println("exitForInit: " + ctx.getText()); }
    @Override public void enterForUpdate(PhpParser.ForUpdateContext ctx) { System.out.println("enterForUpdate: " + ctx.getText()); }
    @Override public void exitForUpdate(PhpParser.ForUpdateContext ctx) { System.out.println("exitForUpdate: " + ctx.getText()); }
    @Override public void enterSwitchStatement(PhpParser.SwitchStatementContext ctx) { System.out.println("enterSwitchStatement: " + ctx.getText()); }
    @Override public void exitSwitchStatement(PhpParser.SwitchStatementContext ctx) { System.out.println("exitSwitchStatement: " + ctx.getText()); }
    @Override public void enterSwitchBlock(PhpParser.SwitchBlockContext ctx) { System.out.println("enterSwitchBlock: " + ctx.getText()); }
    @Override public void exitSwitchBlock(PhpParser.SwitchBlockContext ctx) { System.out.println("exitSwitchBlock: " + ctx.getText()); }
    @Override public void enterBreakStatement(PhpParser.BreakStatementContext ctx) { System.out.println("enterBreakStatement: " + ctx.getText()); }
    @Override public void exitBreakStatement(PhpParser.BreakStatementContext ctx) { System.out.println("exitBreakStatement: " + ctx.getText()); }
    @Override public void enterContinueStatement(PhpParser.ContinueStatementContext ctx) { System.out.println("enterContinueStatement: " + ctx.getText()); }
    @Override public void exitContinueStatement(PhpParser.ContinueStatementContext ctx) { System.out.println("exitContinueStatement: " + ctx.getText()); }
    @Override public void enterReturnStatement(PhpParser.ReturnStatementContext ctx) { System.out.println("enterReturnStatement: " + ctx.getText()); }
    @Override public void exitReturnStatement(PhpParser.ReturnStatementContext ctx) { System.out.println("exitReturnStatement: " + ctx.getText()); }
    @Override public void enterExpressionStatement(PhpParser.ExpressionStatementContext ctx) { System.out.println("enterExpressionStatement: " + ctx.getText()); }
    @Override public void exitExpressionStatement(PhpParser.ExpressionStatementContext ctx) { System.out.println("exitExpressionStatement: " + ctx.getText()); }
    @Override public void enterUnsetStatement(PhpParser.UnsetStatementContext ctx) { System.out.println("enterUnsetStatement: " + ctx.getText()); }
    @Override public void exitUnsetStatement(PhpParser.UnsetStatementContext ctx) { System.out.println("exitUnsetStatement: " + ctx.getText()); }
    @Override public void enterForeachStatement(PhpParser.ForeachStatementContext ctx) { System.out.println("enterForeachStatement: " + ctx.getText()); }
    @Override public void exitForeachStatement(PhpParser.ForeachStatementContext ctx) { System.out.println("exitForeachStatement: " + ctx.getText()); }
    @Override public void enterTryCatchFinally(PhpParser.TryCatchFinallyContext ctx) { System.out.println("enterTryCatchFinally: " + ctx.getText()); }
    @Override public void exitTryCatchFinally(PhpParser.TryCatchFinallyContext ctx) { System.out.println("exitTryCatchFinally: " + ctx.getText()); }
    @Override public void enterCatchClause(PhpParser.CatchClauseContext ctx) { System.out.println("enterCatchClause: " + ctx.getText()); }
    @Override public void exitCatchClause(PhpParser.CatchClauseContext ctx) { System.out.println("exitCatchClause: " + ctx.getText()); }
    @Override public void enterFinallyStatement(PhpParser.FinallyStatementContext ctx) { System.out.println("enterFinallyStatement: " + ctx.getText()); }
    @Override public void exitFinallyStatement(PhpParser.FinallyStatementContext ctx) { System.out.println("exitFinallyStatement: " + ctx.getText()); }
    @Override public void enterThrowStatement(PhpParser.ThrowStatementContext ctx) { System.out.println("enterThrowStatement: " + ctx.getText()); }
    @Override public void exitThrowStatement(PhpParser.ThrowStatementContext ctx) { System.out.println("exitThrowStatement: " + ctx.getText()); }
    @Override public void enterGotoStatement(PhpParser.GotoStatementContext ctx) { System.out.println("enterGotoStatement: " + ctx.getText()); }
    @Override public void exitGotoStatement(PhpParser.GotoStatementContext ctx) { System.out.println("exitGotoStatement: " + ctx.getText()); }
    @Override public void enterDeclareStatement(PhpParser.DeclareStatementContext ctx) { System.out.println("enterDeclareStatement: " + ctx.getText()); }
    @Override public void exitDeclareStatement(PhpParser.DeclareStatementContext ctx) { System.out.println("exitDeclareStatement: " + ctx.getText()); }
    @Override public void enterInlineHtmlStatement(PhpParser.InlineHtmlStatementContext ctx) { System.out.println("enterInlineHtmlStatement: " + ctx.getText()); }
    @Override public void exitInlineHtmlStatement(PhpParser.InlineHtmlStatementContext ctx) { System.out.println("exitInlineHtmlStatement: " + ctx.getText()); }
    @Override public void enterInlineHtml(PhpParser.InlineHtmlContext ctx) { System.out.println("enterInlineHtml: " + ctx.getText()); }
    @Override public void exitInlineHtml(PhpParser.InlineHtmlContext ctx) { System.out.println("exitInlineHtml: " + ctx.getText()); }
    @Override public void enterDeclareList(PhpParser.DeclareListContext ctx) { System.out.println("enterDeclareList: " + ctx.getText()); }
    @Override public void exitDeclareList(PhpParser.DeclareListContext ctx) { System.out.println("exitDeclareList: " + ctx.getText()); }
    @Override public void enterFormalParameterList(PhpParser.FormalParameterListContext ctx) { System.out.println("enterFormalParameterList: " + ctx.getText()); }
    @Override public void exitFormalParameterList(PhpParser.FormalParameterListContext ctx) { System.out.println("exitFormalParameterList: " + ctx.getText()); }
    @Override public void enterFormalParameter(PhpParser.FormalParameterContext ctx) { System.out.println("enterFormalParameter: " + ctx.getText()); }
    @Override public void exitFormalParameter(PhpParser.FormalParameterContext ctx) { System.out.println("exitFormalParameter: " + ctx.getText()); }
    @Override public void enterTypeHint(PhpParser.TypeHintContext ctx) { System.out.println("enterTypeHint: " + ctx.getText()); }
    @Override public void exitTypeHint(PhpParser.TypeHintContext ctx) { System.out.println("exitTypeHint: " + ctx.getText()); }
    @Override public void enterGlobalStatement(PhpParser.GlobalStatementContext ctx) { System.out.println("enterGlobalStatement: " + ctx.getText()); }
    @Override public void exitGlobalStatement(PhpParser.GlobalStatementContext ctx) { System.out.println("exitGlobalStatement: " + ctx.getText()); }
    @Override public void enterGlobalVar(PhpParser.GlobalVarContext ctx) { System.out.println("enterGlobalVar: " + ctx.getText()); }
    @Override public void exitGlobalVar(PhpParser.GlobalVarContext ctx) { System.out.println("exitGlobalVar: " + ctx.getText()); }
    @Override public void enterEchoStatement(PhpParser.EchoStatementContext ctx) { System.out.println("enterEchoStatement: " + ctx.getText()); }
    @Override public void exitEchoStatement(PhpParser.EchoStatementContext ctx) { System.out.println("exitEchoStatement: " + ctx.getText()); }
    @Override public void enterStaticVariableStatement(PhpParser.StaticVariableStatementContext ctx) { System.out.println("enterStaticVariableStatement: " + ctx.getText()); }
    @Override public void exitStaticVariableStatement(PhpParser.StaticVariableStatementContext ctx) { System.out.println("exitStaticVariableStatement: " + ctx.getText()); }
    @Override public void enterClassStatement(PhpParser.ClassStatementContext ctx) { System.out.println("enterClassStatement: " + ctx.getText()); }
    @Override public void exitClassStatement(PhpParser.ClassStatementContext ctx) { System.out.println("exitClassStatement: " + ctx.getText()); }
    @Override public void enterTraitAdaptations(PhpParser.TraitAdaptationsContext ctx) { System.out.println("enterTraitAdaptations: " + ctx.getText()); }
    @Override public void exitTraitAdaptations(PhpParser.TraitAdaptationsContext ctx) { System.out.println("exitTraitAdaptations: " + ctx.getText()); }
    @Override public void enterTraitAdaptationStatement(PhpParser.TraitAdaptationStatementContext ctx) { System.out.println("enterTraitAdaptationStatement: " + ctx.getText()); }
    @Override public void exitTraitAdaptationStatement(PhpParser.TraitAdaptationStatementContext ctx) { System.out.println("exitTraitAdaptationStatement: " + ctx.getText()); }
    @Override public void enterTraitPrecedence(PhpParser.TraitPrecedenceContext ctx) { System.out.println("enterTraitPrecedence: " + ctx.getText()); }
    @Override public void exitTraitPrecedence(PhpParser.TraitPrecedenceContext ctx) { System.out.println("exitTraitPrecedence: " + ctx.getText()); }
    @Override public void enterTraitAlias(PhpParser.TraitAliasContext ctx) { System.out.println("enterTraitAlias: " + ctx.getText()); }
    @Override public void exitTraitAlias(PhpParser.TraitAliasContext ctx) { System.out.println("exitTraitAlias: " + ctx.getText()); }
    @Override public void enterTraitMethodReference(PhpParser.TraitMethodReferenceContext ctx) { System.out.println("enterTraitMethodReference: " + ctx.getText()); }
    @Override public void exitTraitMethodReference(PhpParser.TraitMethodReferenceContext ctx) { System.out.println("exitTraitMethodReference: " + ctx.getText()); }
    @Override public void enterBaseCtorCall(PhpParser.BaseCtorCallContext ctx) { System.out.println("enterBaseCtorCall: " + ctx.getText()); }
    @Override public void exitBaseCtorCall(PhpParser.BaseCtorCallContext ctx) { System.out.println("exitBaseCtorCall: " + ctx.getText()); }
    @Override public void enterMethodBody(PhpParser.MethodBodyContext ctx) { System.out.println("enterMethodBody: " + ctx.getText()); }
    @Override public void exitMethodBody(PhpParser.MethodBodyContext ctx) { System.out.println("exitMethodBody: " + ctx.getText()); }
    @Override public void enterPropertyModifiers(PhpParser.PropertyModifiersContext ctx) { System.out.println("enterPropertyModifiers: " + ctx.getText()); }
    @Override public void exitPropertyModifiers(PhpParser.PropertyModifiersContext ctx) { System.out.println("exitPropertyModifiers: " + ctx.getText()); }
    @Override public void enterMemberModifiers(PhpParser.MemberModifiersContext ctx) { System.out.println("enterMemberModifiers: " + ctx.getText()); }
    @Override public void exitMemberModifiers(PhpParser.MemberModifiersContext ctx) { System.out.println("exitMemberModifiers: " + ctx.getText()); }
    @Override public void enterVariableInitializer(PhpParser.VariableInitializerContext ctx) { System.out.println("enterVariableInitializer: " + ctx.getText()); }
    @Override public void exitVariableInitializer(PhpParser.VariableInitializerContext ctx) { System.out.println("exitVariableInitializer: " + ctx.getText()); }
    @Override public void enterIdentifierInititalizer(PhpParser.IdentifierInititalizerContext ctx) { System.out.println("enterIdentifierInititalizer: " + ctx.getText()); }
    @Override public void exitIdentifierInititalizer(PhpParser.IdentifierInititalizerContext ctx) { System.out.println("exitIdentifierInititalizer: " + ctx.getText()); }
    @Override public void enterGlobalConstantDeclaration(PhpParser.GlobalConstantDeclarationContext ctx) { System.out.println("enterGlobalConstantDeclaration: " + ctx.getText()); }
    @Override public void exitGlobalConstantDeclaration(PhpParser.GlobalConstantDeclarationContext ctx) { System.out.println("exitGlobalConstantDeclaration: " + ctx.getText()); }
    @Override public void enterExpressionList(PhpParser.ExpressionListContext ctx) { System.out.println("enterExpressionList: " + ctx.getText()); }
    @Override public void exitExpressionList(PhpParser.ExpressionListContext ctx) { System.out.println("exitExpressionList: " + ctx.getText()); }
    @Override public void enterParenthesis(PhpParser.ParenthesisContext ctx) { System.out.println("enterParenthesis: " + ctx.getText()); }
    @Override public void exitParenthesis(PhpParser.ParenthesisContext ctx) { System.out.println("exitParenthesis: " + ctx.getText()); }
    @Override public void enterChainExpression(PhpParser.ChainExpressionContext ctx) { System.out.println("enterChainExpression: " + ctx.getText()); }
    @Override public void exitChainExpression(PhpParser.ChainExpressionContext ctx) { System.out.println("exitChainExpression: " + ctx.getText()); }
    @Override public void enterUnaryOperatorExpression(PhpParser.UnaryOperatorExpressionContext ctx) { System.out.println("enterUnaryOperatorExpression: " + ctx.getText()); }
    @Override public void exitUnaryOperatorExpression(PhpParser.UnaryOperatorExpressionContext ctx) { System.out.println("exitUnaryOperatorExpression: " + ctx.getText()); }
    @Override public void enterSpecialWordExpression(PhpParser.SpecialWordExpressionContext ctx) { System.out.println("enterSpecialWordExpression: " + ctx.getText()); }
    @Override public void exitSpecialWordExpression(PhpParser.SpecialWordExpressionContext ctx) { System.out.println("exitSpecialWordExpression: " + ctx.getText()); }
    @Override public void enterArrayCreationExpression(PhpParser.ArrayCreationExpressionContext ctx) { System.out.println("enterArrayCreationExpression: " + ctx.getText()); }
    @Override public void exitArrayCreationExpression(PhpParser.ArrayCreationExpressionContext ctx) { System.out.println("exitArrayCreationExpression: " + ctx.getText()); }
    @Override public void enterNewExpression(PhpParser.NewExpressionContext ctx) { System.out.println("enterNewExpression: " + ctx.getText()); }
    @Override public void exitNewExpression(PhpParser.NewExpressionContext ctx) { System.out.println("exitNewExpression: " + ctx.getText()); }
    @Override public void enterParenthesisExpression(PhpParser.ParenthesisExpressionContext ctx) { System.out.println("enterParenthesisExpression: " + ctx.getText()); }
    @Override public void exitParenthesisExpression(PhpParser.ParenthesisExpressionContext ctx) { System.out.println("exitParenthesisExpression: " + ctx.getText()); }
    @Override public void enterBackQuoteStringExpression(PhpParser.BackQuoteStringExpressionContext ctx) { System.out.println("enterBackQuoteStringExpression: " + ctx.getText()); }
    @Override public void exitBackQuoteStringExpression(PhpParser.BackQuoteStringExpressionContext ctx) { System.out.println("exitBackQuoteStringExpression: " + ctx.getText()); }
    @Override public void enterConditionalExpression(PhpParser.ConditionalExpressionContext ctx) { System.out.println("enterConditionalExpression: " + ctx.getText()); }
    @Override public void exitConditionalExpression(PhpParser.ConditionalExpressionContext ctx) { System.out.println("exitConditionalExpression: " + ctx.getText()); }
    @Override public void enterArithmeticExpression(PhpParser.ArithmeticExpressionContext ctx) { System.out.println("enterArithmeticExpression: " + ctx.getText()); }
    @Override public void exitArithmeticExpression(PhpParser.ArithmeticExpressionContext ctx) { System.out.println("exitArithmeticExpression: " + ctx.getText()); }
    @Override public void enterIndexerExpression(PhpParser.IndexerExpressionContext ctx) { System.out.println("enterIndexerExpression: " + ctx.getText()); }
    @Override public void exitIndexerExpression(PhpParser.IndexerExpressionContext ctx) { System.out.println("exitIndexerExpression: " + ctx.getText()); }
    @Override public void enterScalarExpression(PhpParser.ScalarExpressionContext ctx) { System.out.println("enterScalarExpression: " + ctx.getText()); }
    @Override public void exitScalarExpression(PhpParser.ScalarExpressionContext ctx) { System.out.println("exitScalarExpression: " + ctx.getText()); }
    @Override public void enterPrefixIncDecExpression(PhpParser.PrefixIncDecExpressionContext ctx) { System.out.println("enterPrefixIncDecExpression: " + ctx.getText()); }
    @Override public void exitPrefixIncDecExpression(PhpParser.PrefixIncDecExpressionContext ctx) { System.out.println("exitPrefixIncDecExpression: " + ctx.getText()); }
    @Override public void enterComparisonExpression(PhpParser.ComparisonExpressionContext ctx) { System.out.println("enterComparisonExpression: " + ctx.getText()); }
    @Override public void exitComparisonExpression(PhpParser.ComparisonExpressionContext ctx) { System.out.println("exitComparisonExpression: " + ctx.getText()); }
    @Override public void enterLogicalExpression(PhpParser.LogicalExpressionContext ctx) { System.out.println("enterLogicalExpression: " + ctx.getText()); }
    @Override public void exitLogicalExpression(PhpParser.LogicalExpressionContext ctx) { System.out.println("exitLogicalExpression: " + ctx.getText()); }
    @Override public void enterPrintExpression(PhpParser.PrintExpressionContext ctx) { System.out.println("enterPrintExpression: " + ctx.getText()); }
    @Override public void exitPrintExpression(PhpParser.PrintExpressionContext ctx) { System.out.println("exitPrintExpression: " + ctx.getText()); }
    @Override public void enterAssignmentExpression(PhpParser.AssignmentExpressionContext ctx) { System.out.println("enterAssignmentExpression: " + ctx.getText()); }
    @Override public void exitAssignmentExpression(PhpParser.AssignmentExpressionContext ctx) { System.out.println("exitAssignmentExpression: " + ctx.getText()); }
    @Override public void enterPostfixIncDecExpression(PhpParser.PostfixIncDecExpressionContext ctx) { System.out.println("enterPostfixIncDecExpression: " + ctx.getText()); }
    @Override public void exitPostfixIncDecExpression(PhpParser.PostfixIncDecExpressionContext ctx) { System.out.println("exitPostfixIncDecExpression: " + ctx.getText()); }
    @Override public void enterCastExpression(PhpParser.CastExpressionContext ctx) { System.out.println("enterCastExpression: " + ctx.getText()); }
    @Override public void exitCastExpression(PhpParser.CastExpressionContext ctx) { System.out.println("exitCastExpression: " + ctx.getText()); }
    @Override public void enterInstanceOfExpression(PhpParser.InstanceOfExpressionContext ctx) { System.out.println("enterInstanceOfExpression: " + ctx.getText()); }
    @Override public void exitInstanceOfExpression(PhpParser.InstanceOfExpressionContext ctx) { System.out.println("exitInstanceOfExpression: " + ctx.getText()); }
    @Override public void enterLambdaFunctionExpression(PhpParser.LambdaFunctionExpressionContext ctx) { System.out.println("enterLambdaFunctionExpression: " + ctx.getText()); }
    @Override public void exitLambdaFunctionExpression(PhpParser.LambdaFunctionExpressionContext ctx) { System.out.println("exitLambdaFunctionExpression: " + ctx.getText()); }
    @Override public void enterBitwiseExpression(PhpParser.BitwiseExpressionContext ctx) { System.out.println("enterBitwiseExpression: " + ctx.getText()); }
    @Override public void exitBitwiseExpression(PhpParser.BitwiseExpressionContext ctx) { System.out.println("exitBitwiseExpression: " + ctx.getText()); }
    @Override public void enterCloneExpression(PhpParser.CloneExpressionContext ctx) { System.out.println("enterCloneExpression: " + ctx.getText()); }
    @Override public void exitCloneExpression(PhpParser.CloneExpressionContext ctx) { System.out.println("exitCloneExpression: " + ctx.getText()); }
    @Override public void enterNewExpr(PhpParser.NewExprContext ctx) { System.out.println("enterNewExpr: " + ctx.getText()); }
    @Override public void exitNewExpr(PhpParser.NewExprContext ctx) { System.out.println("exitNewExpr: " + ctx.getText()); }
    @Override public void enterAssignmentOperator(PhpParser.AssignmentOperatorContext ctx) { System.out.println("enterAssignmentOperator: " + ctx.getText()); }
    @Override public void exitAssignmentOperator(PhpParser.AssignmentOperatorContext ctx) { System.out.println("exitAssignmentOperator: " + ctx.getText()); }
    @Override public void enterYieldExpression(PhpParser.YieldExpressionContext ctx) { System.out.println("enterYieldExpression: " + ctx.getText()); }
    @Override public void exitYieldExpression(PhpParser.YieldExpressionContext ctx) { System.out.println("exitYieldExpression: " + ctx.getText()); }
    @Override public void enterArrayItemList(PhpParser.ArrayItemListContext ctx) { System.out.println("enterArrayItemList: " + ctx.getText()); }
    @Override public void exitArrayItemList(PhpParser.ArrayItemListContext ctx) { System.out.println("exitArrayItemList: " + ctx.getText()); }
    @Override public void enterArrayItem(PhpParser.ArrayItemContext ctx) { System.out.println("enterArrayItem: " + ctx.getText()); }
    @Override public void exitArrayItem(PhpParser.ArrayItemContext ctx) { System.out.println("exitArrayItem: " + ctx.getText()); }
    @Override public void enterLambdaFunctionUseVars(PhpParser.LambdaFunctionUseVarsContext ctx) { System.out.println("enterLambdaFunctionUseVars: " + ctx.getText()); }
    @Override public void exitLambdaFunctionUseVars(PhpParser.LambdaFunctionUseVarsContext ctx) { System.out.println("exitLambdaFunctionUseVars: " + ctx.getText()); }
    @Override public void enterLambdaFunctionUseVar(PhpParser.LambdaFunctionUseVarContext ctx) { System.out.println("enterLambdaFunctionUseVar: " + ctx.getText()); }
    @Override public void exitLambdaFunctionUseVar(PhpParser.LambdaFunctionUseVarContext ctx) { System.out.println("exitLambdaFunctionUseVar: " + ctx.getText()); }
    @Override public void enterQualifiedStaticTypeRef(PhpParser.QualifiedStaticTypeRefContext ctx) { System.out.println("enterQualifiedStaticTypeRef: " + ctx.getText()); }
    @Override public void exitQualifiedStaticTypeRef(PhpParser.QualifiedStaticTypeRefContext ctx) { System.out.println("exitQualifiedStaticTypeRef: " + ctx.getText()); }
    @Override public void enterTypeRef(PhpParser.TypeRefContext ctx) { System.out.println("enterTypeRef: " + ctx.getText()); }
    @Override public void exitTypeRef(PhpParser.TypeRefContext ctx) { System.out.println("exitTypeRef: " + ctx.getText()); }
    @Override public void enterIndirectTypeRef(PhpParser.IndirectTypeRefContext ctx) { System.out.println("enterIndirectTypeRef: " + ctx.getText()); }
    @Override public void exitIndirectTypeRef(PhpParser.IndirectTypeRefContext ctx) { System.out.println("exitIndirectTypeRef: " + ctx.getText()); }
    @Override public void enterQualifiedNamespaceName(PhpParser.QualifiedNamespaceNameContext ctx) { System.out.println("enterQualifiedNamespaceName: " + ctx.getText()); }
    @Override public void exitQualifiedNamespaceName(PhpParser.QualifiedNamespaceNameContext ctx) { System.out.println("exitQualifiedNamespaceName: " + ctx.getText()); }
    @Override public void enterNamespaceNameList(PhpParser.NamespaceNameListContext ctx) { System.out.println("enterNamespaceNameList: " + ctx.getText()); }
    @Override public void exitNamespaceNameList(PhpParser.NamespaceNameListContext ctx) { System.out.println("exitNamespaceNameList: " + ctx.getText()); }
    @Override public void enterQualifiedNamespaceNameList(PhpParser.QualifiedNamespaceNameListContext ctx) { System.out.println("enterQualifiedNamespaceNameList: " + ctx.getText()); }
    @Override public void exitQualifiedNamespaceNameList(PhpParser.QualifiedNamespaceNameListContext ctx) { System.out.println("exitQualifiedNamespaceNameList: " + ctx.getText()); }
    @Override public void enterArguments(PhpParser.ArgumentsContext ctx) { System.out.println("enterArguments: " + ctx.getText()); }
    @Override public void exitArguments(PhpParser.ArgumentsContext ctx) { System.out.println("exitArguments: " + ctx.getText()); }
    @Override public void enterActualArgument(PhpParser.ActualArgumentContext ctx) { System.out.println("enterActualArgument: " + ctx.getText()); }
    @Override public void exitActualArgument(PhpParser.ActualArgumentContext ctx) { System.out.println("exitActualArgument: " + ctx.getText()); }
    @Override public void enterConstantInititalizer(PhpParser.ConstantInititalizerContext ctx) { System.out.println("enterConstantInititalizer: " + ctx.getText()); }
    @Override public void exitConstantInititalizer(PhpParser.ConstantInititalizerContext ctx) { System.out.println("exitConstantInititalizer: " + ctx.getText()); }
    @Override public void enterConstantArrayItemList(PhpParser.ConstantArrayItemListContext ctx) { System.out.println("enterConstantArrayItemList: " + ctx.getText()); }
    @Override public void exitConstantArrayItemList(PhpParser.ConstantArrayItemListContext ctx) { System.out.println("exitConstantArrayItemList: " + ctx.getText()); }
    @Override public void enterConstantArrayItem(PhpParser.ConstantArrayItemContext ctx) { System.out.println("enterConstantArrayItem: " + ctx.getText()); }
    @Override public void exitConstantArrayItem(PhpParser.ConstantArrayItemContext ctx) { System.out.println("exitConstantArrayItem: " + ctx.getText()); }
    @Override public void enterConstant(PhpParser.ConstantContext ctx) { System.out.println("enterConstant: " + ctx.getText()); }
    @Override public void exitConstant(PhpParser.ConstantContext ctx) { System.out.println("exitConstant: " + ctx.getText()); }
    @Override public void enterLiteralConstant(PhpParser.LiteralConstantContext ctx) { System.out.println("enterLiteralConstant: " + ctx.getText()); }
    @Override public void exitLiteralConstant(PhpParser.LiteralConstantContext ctx) { System.out.println("exitLiteralConstant: " + ctx.getText()); }
    @Override public void enterNumericConstant(PhpParser.NumericConstantContext ctx) { System.out.println("enterNumericConstant: " + ctx.getText()); }
    @Override public void exitNumericConstant(PhpParser.NumericConstantContext ctx) { System.out.println("exitNumericConstant: " + ctx.getText()); }
    @Override public void enterClassConstant(PhpParser.ClassConstantContext ctx) { System.out.println("enterClassConstant: " + ctx.getText()); }
    @Override public void exitClassConstant(PhpParser.ClassConstantContext ctx) { System.out.println("exitClassConstant: " + ctx.getText()); }
    @Override public void enterStringConstant(PhpParser.StringConstantContext ctx) { System.out.println("enterStringConstant: " + ctx.getText()); }
    @Override public void exitStringConstant(PhpParser.StringConstantContext ctx) { System.out.println("exitStringConstant: " + ctx.getText()); }
    @Override public void enterString(PhpParser.StringContext ctx) { System.out.println("enterString: " + ctx.getText()); }
    @Override public void exitString(PhpParser.StringContext ctx) { System.out.println("exitString: " + ctx.getText()); }
    @Override public void enterInterpolatedStringPart(PhpParser.InterpolatedStringPartContext ctx) { System.out.println("enterInterpolatedStringPart: " + ctx.getText()); }
    @Override public void exitInterpolatedStringPart(PhpParser.InterpolatedStringPartContext ctx) { System.out.println("exitInterpolatedStringPart: " + ctx.getText()); }
    @Override public void enterChainList(PhpParser.ChainListContext ctx) { System.out.println("enterChainList: " + ctx.getText()); }
    @Override public void exitChainList(PhpParser.ChainListContext ctx) { System.out.println("exitChainList: " + ctx.getText()); }
    @Override public void enterChain(PhpParser.ChainContext ctx) { System.out.println("enterChain: " + ctx.getText()); }
    @Override public void exitChain(PhpParser.ChainContext ctx) { System.out.println("exitChain: " + ctx.getText()); }
    @Override public void enterMemberAccess(PhpParser.MemberAccessContext ctx) { System.out.println("enterMemberAccess: " + ctx.getText()); }
    @Override public void exitMemberAccess(PhpParser.MemberAccessContext ctx) { System.out.println("exitMemberAccess: " + ctx.getText()); }
    @Override public void enterFunctionCall(PhpParser.FunctionCallContext ctx) { System.out.println("enterFunctionCall: " + ctx.getText()); }
    @Override public void exitFunctionCall(PhpParser.FunctionCallContext ctx) { System.out.println("exitFunctionCall: " + ctx.getText()); }
    @Override public void enterFunctionCallName(PhpParser.FunctionCallNameContext ctx) { System.out.println("enterFunctionCallName: " + ctx.getText()); }
    @Override public void exitFunctionCallName(PhpParser.FunctionCallNameContext ctx) { System.out.println("exitFunctionCallName: " + ctx.getText()); }
    @Override public void enterActualArguments(PhpParser.ActualArgumentsContext ctx) { System.out.println("enterActualArguments: " + ctx.getText()); }
    @Override public void exitActualArguments(PhpParser.ActualArgumentsContext ctx) { System.out.println("exitActualArguments: " + ctx.getText()); }
    @Override public void enterChainBase(PhpParser.ChainBaseContext ctx) { System.out.println("enterChainBase: " + ctx.getText()); }
    @Override public void exitChainBase(PhpParser.ChainBaseContext ctx) { System.out.println("exitChainBase: " + ctx.getText()); }
    @Override public void enterKeyedFieldName(PhpParser.KeyedFieldNameContext ctx) { System.out.println("enterKeyedFieldName: " + ctx.getText()); }
    @Override public void exitKeyedFieldName(PhpParser.KeyedFieldNameContext ctx) { System.out.println("exitKeyedFieldName: " + ctx.getText()); }
    @Override public void enterKeyedSimpleFieldName(PhpParser.KeyedSimpleFieldNameContext ctx) { System.out.println("enterKeyedSimpleFieldName: " + ctx.getText()); }
    @Override public void exitKeyedSimpleFieldName(PhpParser.KeyedSimpleFieldNameContext ctx) { System.out.println("exitKeyedSimpleFieldName: " + ctx.getText()); }
    @Override public void enterKeyedVariable(PhpParser.KeyedVariableContext ctx) { System.out.println("enterKeyedVariable: " + ctx.getText()); }
    @Override public void exitKeyedVariable(PhpParser.KeyedVariableContext ctx) { System.out.println("exitKeyedVariable: " + ctx.getText()); }
    @Override public void enterSquareCurlyExpression(PhpParser.SquareCurlyExpressionContext ctx) { System.out.println("enterSquareCurlyExpression: " + ctx.getText()); }
    @Override public void exitSquareCurlyExpression(PhpParser.SquareCurlyExpressionContext ctx) { System.out.println("exitSquareCurlyExpression: " + ctx.getText()); }
    @Override public void enterAssignmentList(PhpParser.AssignmentListContext ctx) { System.out.println("enterAssignmentList: " + ctx.getText()); }
    @Override public void exitAssignmentList(PhpParser.AssignmentListContext ctx) { System.out.println("exitAssignmentList: " + ctx.getText()); }
    @Override public void enterAssignmentListElement(PhpParser.AssignmentListElementContext ctx) { System.out.println("enterAssignmentListElement: " + ctx.getText()); }
    @Override public void exitAssignmentListElement(PhpParser.AssignmentListElementContext ctx) { System.out.println("exitAssignmentListElement: " + ctx.getText()); }
    @Override public void enterModifier(PhpParser.ModifierContext ctx) { System.out.println("enterModifier: " + ctx.getText()); }
    @Override public void exitModifier(PhpParser.ModifierContext ctx) { System.out.println("exitModifier: " + ctx.getText()); }
    @Override public void enterIdentifier(PhpParser.IdentifierContext ctx) { System.out.println("enterIdentifier: " + ctx.getText()); }
    @Override public void exitIdentifier(PhpParser.IdentifierContext ctx) { System.out.println("exitIdentifier: " + ctx.getText()); }
    @Override public void enterMemberModifier(PhpParser.MemberModifierContext ctx) { System.out.println("enterMemberModifier: " + ctx.getText()); }
    @Override public void exitMemberModifier(PhpParser.MemberModifierContext ctx) { System.out.println("exitMemberModifier: " + ctx.getText()); }
    @Override public void enterMagicConstant(PhpParser.MagicConstantContext ctx) { System.out.println("enterMagicConstant: " + ctx.getText()); }
    @Override public void exitMagicConstant(PhpParser.MagicConstantContext ctx) { System.out.println("exitMagicConstant: " + ctx.getText()); }
    @Override public void enterMagicMethod(PhpParser.MagicMethodContext ctx) { System.out.println("enterMagicMethod: " + ctx.getText()); }
    @Override public void exitMagicMethod(PhpParser.MagicMethodContext ctx) { System.out.println("exitMagicMethod: " + ctx.getText()); }
    @Override public void enterPrimitiveType(PhpParser.PrimitiveTypeContext ctx) { System.out.println("enterPrimitiveType: " + ctx.getText()); }
    @Override public void exitPrimitiveType(PhpParser.PrimitiveTypeContext ctx) { System.out.println("exitPrimitiveType: " + ctx.getText()); }
    @Override public void enterCastOperation(PhpParser.CastOperationContext ctx) { System.out.println("enterCastOperation: " + ctx.getText()); }
    @Override public void exitCastOperation(PhpParser.CastOperationContext ctx) { System.out.println("exitCastOperation: " + ctx.getText()); }
    @Override public void enterEveryRule(ParserRuleContext ctx) { System.out.println("enterEveryRule: " + ctx.getText()); }
    @Override public void exitEveryRule(ParserRuleContext ctx) { System.out.println("exitEveryRule: " + ctx.getText()); }
    @Override public void visitTerminal(TerminalNode node) { System.out.println("visitTerminal: " + node.getText()); }
    @Override public void visitErrorNode(ErrorNode node) { System.out.println("visitErrorNode: " + node.getText()); }
}
